## [Numpy 배열 프로그래밍](http://datascienceschool.net/01%20python/03.00%203%EC%9E%A5%20%EB%84%98%ED%8C%8C%EC%9D%B4%20%EB%B0%B0%EC%97%B4%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D.html)

> [데이터 사이언스 스쿨](http://datascienceschool.net/intro.html)의 연습문제를 풀이합니다.

많은 숫자 데이터를 하나의 변수에 넣고 관리 할 때 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 배열(array)을 사용하면 적은 메모리로 많은 데이터를 빠르게 처리할 수 있다.

In [2]:
# 넘파이 패키지 임포트

import numpy as np

In [4]:
# 연습문제 3.1.1

result = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
print(result)

[[10 20 30 40]
 [50 60 70 80]]


In [10]:
# 연습문제 3.1.2

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

print(m[1][2])
print(m[2][-1])
print(m[1,1:3])
print(m[1:3,2])
print(m[0:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [17]:
# 연습문제 3.1.3

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(x[x%3 == 0])
print(x[x%4 == 1])
print(x[(x%3==0) & (x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [30]:
# 연습문제 3.2.1

a1 = np.zeros((3,3))
a2 = np.ones((3,2))
b1 = np.arange(10,151,10).reshape(3,-1)

c1 = np.hstack([a1,a2])
d1 = np.vstack([c1,b1])

result = np.tile(d1,(2,1))
print(result)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


In [52]:
# 연습문제 3.3.1

a = np.arange(30, dtype='f')
a = a.reshape(5,6)
print(a)

print('1번: ', a.max())
print('2번: ', a.sum(axis=1))
print('3번: ', a.max(axis=1))
print('4번: ', a.mean(axis=0))
print('5번: ', a.min(axis=0))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]
1번:  29.0
2번:  [ 15.  51.  87. 123. 159.]
3번:  [ 5. 11. 17. 23. 29.]
4번:  [12. 13. 14. 15. 16. 17.]
5번:  [0. 1. 2. 3. 4. 5.]


In [72]:
# 연습문제 3.3.2

a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

english_sort  = np.argsort(a[1])
print(english_sort)

a[:, english_sort]

[0 3 1 2]


array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [83]:
# 연습문제 3.5.1

result1 = np.random.rand(10)*2//1
print(result1)

result2 = np.random.rand(100)*2//1
print(result2.mean())

[1. 1. 1. 0. 1. 0. 1. 0. 0. 1.]
0.57


In [85]:
# 연습문제 3.5.2

result = 10000 + np.random.randn(250)
print(result)

[ 9999.57067601 10000.54257933  9998.61062486 10000.239678
 10000.93167897  9999.0323735  10000.82783405  9999.60362156
  9999.84984179  9999.99806736 10000.05498525 10000.5547343
  9999.64432282  9999.91460865 10000.16315621  9999.03199179
  9999.26292827 10000.73311469 10000.77742355  9999.15083959
  9998.60048499  9999.88912522  9999.45530043 10001.90519218
  9999.74955097  9999.53872414  9999.75953876 10001.31239623
 10000.07745414  9999.97364563  9998.94791941  9999.79537455
  9999.56943982  9997.51201203 10000.51331891 10000.27314904
 10000.52367048  9998.20465437  9999.23111227  9998.66110565
  9999.78143771 10000.9062098  10000.43346977 10000.35695811
  9999.4126227   9998.99688466  9999.41209246  9998.8944407
  9999.47618708  9999.46028868  9998.13707724 10000.0610352
 10000.18081434 10000.898151    9999.5909605  10000.9982462
  9998.6780912   9998.8142026  10001.04062431 10000.48251243
  9998.82694279 10000.68175069  9999.92436714 10001.83594297
  9998.90023694  9998.14492755