> **Elice  Ai Track**에서 제공하는 강의자료를 바탕으로 작성하였습니다.  

##  < NumPy >

고성능의 수치 계산을 위해 만들어진 라이브러리

### 01. NumPy 기본

1. 배열 만들기
   * Numpy 라이브러리는 효율적인 데이터분석이 가능하도록 N차원의 배열 객체를 지원
   * Numpy library에서 자주 사용되는 함수
       * np.array - 배열생성
       * np.zeros - 0이 들어있는 배열 생성
       * np.ones - 1이 들어있는 배열 생성
       * np.empty - 초기화가 없는 값으로 배열을 반환
       * np.arange(n) - 배열 버전의 range 함수
       * np.random - 다양한 난수가 들어있는 배열 생성

In [1]:
# 0 이상 10 미만의 랜덤한 값이 들어가 있는 4X5 배열
import numpy as np

a = np.random.randint(0,10,(4,5))
print(a)

[[9 3 0 1 1]
 [5 9 5 8 6]
 [7 0 0 2 0]
 [3 3 3 9 7]]


2. 배열의 기초
    * 배열의 속성
        * **자료형**: 변수가 가지고 있는 값의 형태의 구분을 의미한다. numpy 배열의 자료형은 **ndarray**이다. 자료형은 파이썬의 내장함수 type()함수로 확인할 수 있다.
        * **차원**: 차원은 배열의 복잡도를 의미한다. 1차원 배열이면 1, 2차원 배열이면 2, n차원 배열이면 n이다. 차원이 하나 늘어날 때 마다 데이터를 담는 방향(축)이 하나씩 늘어나게 됩니다.
        * **모양**: 배열이 자료를 담고 있는 형태를 의미한다. 10개의 자료가 들어있는 1차원 배열의 모양은 (10,)으로 나타내고, 3x3 모양의 2차원 배열은 (3,3)로 나타냅니다.
        * **크기**: 배열이 가지고 있는 자료들의 개수를 의미한다.
        * **dtype**: 배열이 담고 있는 요소들의 자료형을 의미한다. 정수를 담고 있는 배열의 자료형은 ndarray지만, dtype은 **int**이다.

In [2]:
# 1차원 array
import numpy as np

array = np.arange(8)
print(array)

print("자료형 : ", type(array))
print("차원 : ", array.ndim)
print("모양 : ", array.shape)
print("크기 : ", array.size)
print("dtype :", array.dtype)

[0 1 2 3 4 5 6 7]
자료형 :  <class 'numpy.ndarray'>
차원 :  1
모양 :  (8,)
크기 :  8
dtype : int32


In [3]:
# 2차원 matrix
import numpy as np

matrix = np.arange(1, 11).reshape(2,5)
print(matrix)

print("자료형 : ", type(matrix))
print("차원 : ", matrix.ndim)
print("모양 : ", matrix.shape)
print("크기 : ", matrix.size)
print("dtype :", matrix.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
자료형 :  <class 'numpy.ndarray'>
차원 :  2
모양 :  (2, 5)
크기 :  10
dtype : int32


3. 배열의 인덱싱과 슬라이싱
    * 리스트나 배열 연산에서 가장 기초는 배열에서 내가 원하는 요소를 선택하는 것.
    * 인덱싱(Indexing): 값 하나를 선택
    * 슬라이싱(Slicing): 여러 요소를 범위를 지정하여 선택

In [4]:
# 1차원 배열의 indexing, slicing
import numpy as np

array = np.arange(8)   
print(array)

print("array[2] : ", array[2])
print("array[1:4] : ", array[1:4])  # 배열 이름 [시작위치:끝위치+1]

[0 1 2 3 4 5 6 7]
array[2] :  2
array[1:4] :  [1 2 3]


In [5]:
# 2차원 matrix의 indexing, slicing
import numpy as np

matrix = np.arange(1, 11).reshape(2,5)
print(matrix)

print("matrix[1,3] : ", matrix[1,3])
print("matrix[0:2, 0:2] : ", matrix[0:2, 0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
matrix[1,3] :  9
matrix[0:2, 0:2] :  [[1 2]
 [6 7]]


4. 배열 모양 바꾸기
    * Reshape 함수 사용법
    
    ```배열명.reshape(바꿀 모양)```

### 02. NumPy 심화

1. 배열 이어붙이기
    * concatenate() 함수 사용법
    
    ```np.concatenate([배열1, 배열2, 배열3 ... 배열n], axis)```
    
        * axis = 0으로 사용하면 세로 방향으로, axis = 1로 사용하면 가로 방향으로 이어붙입니다.

<br> 

2. 배열 나누기
    * split() 함수
    ```np.split(나눌 배열, [인덱스들], axis)```
    

In [6]:
# split() 함수 사용예시
import numpy as np

A = np.array([[ 0, 1, 2, 3],
              [ 4, 5, 6, 7],
              [ 8, 9,10,11], 
              [12,13,14,15]])
np.split(A, [2], axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [7]:
np.split(A, [1,3], axis = 0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [1]:
# matrix를 axis 0을 활용하여 3번째 행을 기준으로 나누고, 그 결과를 각각 a, b란 변수에 저장
import numpy as np
matrix = np.array([[ 0, 1, 2, 3],
                   [ 4, 5, 6, 7],
                   [ 8, 9,10,11], 
                   [12,13,14,15]])
                   
a, b = np.split(matrix,[3],axis=0)

print(a, "\n")
print(b, "\n")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]] 



3. 기본 연산
    * Numpy의 배열끼리도 사칙연산을 수행할 수 있다.
4. 브로드캐스팅
    * 서로 다른 모양의 배열끼리 산술 연산을 할 때, 작은 쪽의 배열을 큰 쪽의 배열 크기로 확장시켜 연산시키는 것이다.

In [8]:
# 브로드캐스팅 예시
import numpy as np

A = np.array([1,2,3,4,5])
B = np.array([3])
print(A+B)

[4 5 6 7 8]


5. 다양한 집계함수
    * **sum()**
        * matrix의 총 합계를 구할 수 있다.
        ```python
        np.sum(matrix)
        ```
        * matrix의 각 열끼리 더한 값을 구할 수 있다.
        ```
        np.sum(matrix, axis=0)
        ```
        * matrix의 각 행끼리 더한 값을 구할 수 있다.
        ```
        np.sum(matrix, axis=1)
        ```
       
    * **max()** : 최댓값
        ```
        np.max(matrix)
        ```
    * **min()** : 최솟값
        ```
        np.min(matrix)
        ```
    * **mean()** : 평균값
    ```
    np.mean(matrix)
    ```
    * **std()** : 표준편차
    ```
    np.std(matrix)
    ```
    
 6 . 마스킹 연산
 
 * Numpy 배열에서 조건을 만족하는 값만 따로 추출한다.
     * ex) 3 이상 5 이하의 값만 출력
     ```
     print(matrix[(matrix >= 3) & (matrix <= 5)])
     ```

In [12]:
# 마스킹 연산
import numpy as np

matrix = np.arange(8).reshape((2, 4))
print(matrix)

print(matrix[matrix>4])

[[0 1 2 3]
 [4 5 6 7]]
[5 6 7]
